version: "3.9"
services:
  web:
    build:
      context: ./docker-fastapi-mongodb
    ports:
      - "8888:80"
    command: /start-reload.sh
    volumes:
      - ./docker-fastapi-mongodb/app:/app
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
